CREATE DATABASE QuanlySieuthi COLLATE Vietnamese_CI_AS;

USE QuanlySieuthi;

CREATE TABLE LOAI_HANG(
	MaLoai VARCHAR(10) NOT NULL PRIMARY KEY,
	TenLoai NVARCHAR(100) NOT NULL,
	MoTa NVARCHAR(255) NULL
);

CREATE TABLE SAN_PHAM(
    MaSP      VARCHAR(10)   NOT NULL PRIMARY KEY,
    TenSP     NVARCHAR(150) NOT NULL,
    DonGiaBan DECIMAL(15,2) NOT NULL CHECK (DonGiaBan >= 0),
    DonViTinh NVARCHAR(30)  NOT NULL,
    MaLoai    VARCHAR(10)   NOT NULL,
    FOREIGN KEY (MaLoai) REFERENCES LOAI_HANG(MaLoai)
);

CREATE TABLE KHO (
    MaKho     VARCHAR(10)   NOT NULL PRIMARY KEY,
    TenKho    NVARCHAR(100) NOT NULL,
    DiaChiKho NVARCHAR(255) NULL
);

CREATE TABLE LUU_TRU (
    MaSP       VARCHAR(10) NOT NULL,
    MaKho      VARCHAR(10) NOT NULL,
    SoLuongTon INT NOT NULL DEFAULT 0 CHECK (SoLuongTon >= 0),
    PRIMARY KEY (MaSP, MaKho),
    FOREIGN KEY (MaSP)  REFERENCES SAN_PHAM(MaSP),
    FOREIGN KEY (MaKho) REFERENCES KHO(MaKho)
);

CREATE TABLE NHA_CUNG_CAP (
    MaNCC     VARCHAR(10)   NOT NULL PRIMARY KEY,
    TenNCC    NVARCHAR(150) NOT NULL,
    Email     VARCHAR(100)  NULL,
    Duong     NVARCHAR(100) NULL,
    Quan      NVARCHAR(50)  NULL,
    TinhThanh NVARCHAR(50)  NULL
);

CREATE TABLE NHA_CUNG_CAP_SDT (
    MaNCC VARCHAR(10) NOT NULL,
    SDT   VARCHAR(15) NOT NULL,
    PRIMARY KEY (MaNCC, SDT),
    FOREIGN KEY (MaNCC) REFERENCES NHA_CUNG_CAP(MaNCC) ON DELETE CASCADE
);

CREATE TABLE NHAN_VIEN (
    MaNV       VARCHAR(10)   NOT NULL PRIMARY KEY,
    HoDem      NVARCHAR(50)  NOT NULL,
    Ten        NVARCHAR(30)  NOT NULL,
    GioiTinh   NVARCHAR(10)  NULL,
    NgaySinh   DATE          NULL,
    ChucVu     NVARCHAR(50)  NULL,
    LuongCB    DECIMAL(15,2) NULL CHECK (LuongCB >= 0),
    NgayVaoLam DATE          NULL
);

CREATE TABLE NHAN_VIEN_SDT (
    MaNV VARCHAR(10) NOT NULL,
    SDT  VARCHAR(15) NOT NULL,
    PRIMARY KEY (MaNV, SDT),
    FOREIGN KEY (MaNV) REFERENCES NHAN_VIEN(MaNV) ON DELETE CASCADE
);

CREATE TABLE KHACH_HANG (
    MaKH          VARCHAR(10)   NOT NULL PRIMARY KEY,
    HoDem         NVARCHAR(50)  NOT NULL,
    Ten           NVARCHAR(30)  NOT NULL,
    NgaySinh      DATE          NULL,
    LoaiThanhVien NVARCHAR(30)  NULL,
    Email         VARCHAR(100)  NULL,
    Duong         NVARCHAR(100) NULL,
    Quan          NVARCHAR(50)  NULL
);

CREATE TABLE KHACH_HANG_SDT (
    MaKH VARCHAR(10) NOT NULL,
    SDT  VARCHAR(15) NOT NULL,
    PRIMARY KEY (MaKH, SDT),
    FOREIGN KEY (MaKH) REFERENCES KHACH_HANG(MaKH) ON DELETE CASCADE
);

CREATE TABLE PHIEU_NHAP (
    MaPN     VARCHAR(10) NOT NULL PRIMARY KEY,
    NgayNhap DATE        NOT NULL,
    MaNCC    VARCHAR(10) NOT NULL,
    MaNV     VARCHAR(10) NOT NULL,
    FOREIGN KEY (MaNCC) REFERENCES NHA_CUNG_CAP(MaNCC),
    FOREIGN KEY (MaNV)  REFERENCES NHAN_VIEN(MaNV)
);

CREATE TABLE CHI_TIET_NHAP (
    MaPN          VARCHAR(10)   NOT NULL,
    MaSP          VARCHAR(10)   NOT NULL,
    SoLuongNhap   INT           NOT NULL CHECK (SoLuongNhap > 0),
    DonGiaNhap    DECIMAL(15,2) NOT NULL CHECK (DonGiaNhap >= 0),
    ThanhTienNhap AS (SoLuongNhap * DonGiaNhap) PERSISTED,
    PRIMARY KEY (MaPN, MaSP),
    FOREIGN KEY (MaPN) REFERENCES PHIEU_NHAP(MaPN) ON DELETE CASCADE,
    FOREIGN KEY (MaSP) REFERENCES SAN_PHAM(MaSP)
);

CREATE TABLE HOA_DON (
    MaHD         VARCHAR(10)  NOT NULL PRIMARY KEY,
    NgayLap      DATE         NOT NULL,
    PhuongThucTT NVARCHAR(30) NULL,
    TrangThaiTT  NVARCHAR(30) NULL,
    MaKH         VARCHAR(10)  NOT NULL,
    MaNV         VARCHAR(10)  NOT NULL,
    FOREIGN KEY (MaKH) REFERENCES KHACH_HANG(MaKH),
    FOREIGN KEY (MaNV) REFERENCES NHAN_VIEN(MaNV)
);

CREATE TABLE CHI_TIET_HD (
    MaHD      VARCHAR(10)   NOT NULL,
    MaSP      VARCHAR(10)   NOT NULL,
    SoLuong   INT           NOT NULL CHECK (SoLuong > 0),
    DonGiaBan DECIMAL(15,2) NOT NULL CHECK (DonGiaBan >= 0),
    GiamGia   DECIMAL(15,2) NOT NULL DEFAULT 0 CHECK (GiamGia >= 0),
    ThanhTien AS (SoLuong * DonGiaBan - GiamGia) PERSISTED,
    PRIMARY KEY (MaHD, MaSP),
    FOREIGN KEY (MaHD) REFERENCES HOA_DON(MaHD) ON DELETE CASCADE,
    FOREIGN KEY (MaSP) REFERENCES SAN_PHAM(MaSP)
);

